### ISSUE TITLE
In some cases, ResponseContentStr property is empty

### ISSUE THREAD

**Issue by JMKh3r** [fundamentalslib/fundamentals#3]
I try to use TF4HTTPClient component.
I send a GET-request to the server.

If web-server sends the header:
.................................
HTTP/1.1 200 OK
Transfer-Encoding: chunked
.................................
In this case the property ResponseContentStr  has the correct value - the downloaded html-document.

If web-server sends the header:
.................................
HTTP/1.0 200 OK
.................................
and the server does not send header “Transfer-Encoding”.
In this case the property ResponseContentStr is empty.

Tell me please why so?

**Comment by fundamentalslib** [comment]
The server needs to have a Transfer-Encoding, Content-Length or Content-Type header if there is content.
